# Generated by Django 5.2 on 2025-05-18 20:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='about/', verbose_name='Profil Fotoğrafı')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('title', models.CharField(max_length=100, verbose_name='Ünvan')),
                ('short_description', models.TextField(verbose_name='Kısa Açıklama')),
                ('address', models.CharField(max_length=150, verbose_name='Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Sertifika Adı')),
                ('issuer', models.CharField(max_length=200, verbose_name='Veren Kurum')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('credential_url', models.URLField(blank=True, verbose_name='Sertifika Linki')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='Sertifika ID')),
                ('image', models.ImageField(blank=True, upload_to='certificates/', verbose_name='Sertifika Görseli')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Sertifika',
                'verbose_name_plural': 'Sertifikalar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CodeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Kod Kategorisi',
                'verbose_name_plural': 'Kod Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='CodeLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Dil Adı')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='İkon Sınıfı (opsiyonel)')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Kod Dili',
                'verbose_name_plural': 'Kod Dilleri',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'İletişim Bilgisi',
                'verbose_name_plural': 'İletişim Bilgileri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Proje Kategorisi',
                'verbose_name_plural': 'Proje Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Site Adı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('footer_text', models.CharField(blank=True, max_length=255, verbose_name='Footer Yazısı')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('copyright', models.CharField(blank=True, max_length=255, verbose_name='Copyright')),
                ('contact_title', models.CharField(default='İletişim', max_length=100, verbose_name='İletişim Başlığı')),
                ('contact_subtitle', models.TextField(blank=True, null=True, verbose_name='İletişim Alt Başlığı')),
                ('contact_form_title', models.CharField(default='Bana Ulaşın', max_length=100, verbose_name='Form Başlığı')),
                ('contact_form_subtitle', models.TextField(blank=True, null=True, verbose_name='Form Alt Başlığı')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Kategori İkonu (ör: fas fa-code)')),
            ],
            options={
                'verbose_name': 'Yetenek Kategorisi',
                'verbose_name_plural': 'Yetenek Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Etiket',
                'verbose_name_plural': 'Etiketler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CodeExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('code', models.TextField(verbose_name='Kod')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_examples', to='blog.codecategory', verbose_name='Kategori')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_examples', to='blog.codelanguage', verbose_name='Programlama Dili')),
            ],
            options={
                'verbose_name': 'Kod Örneği',
                'verbose_name_plural': 'Kod Örnekleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yetenek Adı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='skills/', verbose_name='Yetenek Görseli')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='blog.skillcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Yetenek',
                'verbose_name_plural': 'Yetenekler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Alt Kategori Adı')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog.category', verbose_name='Ana Kategori')),
            ],
            options={
                'verbose_name': 'Alt Kategori',
                'verbose_name_plural': 'Alt Kategoriler',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Proje Adı')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Proje Görseli')),
                ('project_url', models.URLField(blank=True, verbose_name='Proje Linki')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub Linki')),
                ('button_text', models.CharField(default='Detayları Gör', max_length=50, verbose_name='Buton Metni')),
                ('button_url', models.URLField(blank=True, verbose_name='Buton Linki (opsiyonel)')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='blog.projectcategory', verbose_name='Kategori')),
                ('tags', models.ManyToManyField(related_name='project_tags', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Pozisyon')),
                ('company', models.CharField(max_length=200, verbose_name='Şirket')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('is_current', models.BooleanField(default=False, verbose_name='Devam Ediyor')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='experience_tags', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Deneyim',
                'verbose_name_plural': 'Deneyimler',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Bölüm')),
                ('school', models.CharField(max_length=200, verbose_name='Okul')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('is_current', models.BooleanField(default=False, verbose_name='Devam Ediyor')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='GPA')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='education_tags', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitimler',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Resim')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Kategori')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.subcategory', verbose_name='Alt Kategori')),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_tags', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-created_at'],
            },
        ),
    ]
