# Generated by Django 5.2 on 2025-05-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_codecategory_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV Dosyası'),
        ),
    ]
