# Generated by Django 5.2 on 2025-05-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sitesettings_cv_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-date', 'order'], 'verbose_name': 'Sertifika', 'verbose_name_plural': 'Sertifikalar'},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='slug',
        ),
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='credential_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sertifika ID'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='credential_url',
            field=models.URLField(blank=True, null=True, verbose_name='Sertifika Linki'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Sertifika Görseli'),
        ),
    ]
