# Generated by Django 5.2 on 2025-05-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_certificate_options_remove_certificate_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
