# Generated by Django 5.2 on 2025-05-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_certificate_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Link Başlığı')),
                ('section', models.CharField(help_text='Örnek: home, about, skills, projects, contact', max_length=100, verbose_name="Bölüm ID'si")),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Navbar Link',
                'verbose_name_plural': 'Navbar Linkleri',
                'ordering': ['order'],
            },
        ),
    ]
